spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cloud_file_storage_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
    open-in-view: false
  session:
    timeout: 30m
  data:
    redis:
      port: 6379
      host: localhost
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 300MB

minio:
  endpoint: http://localhost:9000
  access-key: minioAdmin
  secret-key: minioAdmin
  bucket: cloud-storage